zsh_confd="${ZDOTDIR}/zsh.d"

source ${ZDOTDIR}/zshrc.pre

for i in ${zsh_confd}/*; do
   source $i
done

[[ -r "${ZDOTDIR}/.zshrc.local" ]] && source "${ZDOTDIR}/.zshrc.local"

source ${ZDOTDIR}/zshrc.post

#PROMPT='%n@%m %c %# '
